// Code generated by fastssz. DO NOT EDIT.
// Hash: 09dbd25609c2dc49cd1715fa16f265bed7466672ae2857cecc5e09c902434096
// Version: 0.1.3
package gloas

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderPreferencesRequestV1 object to a target array
func (b *BuilderPreferencesRequestV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Field (0) 'Preferences'
	if b.Preferences == nil {
		b.Preferences = new(BuilderPreferencesV1)
	}
	if dst, err = b.Preferences.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'Auth'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Auth'
	if dst, err = b.Auth.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Preferences'
	if b.Preferences == nil {
		b.Preferences = new(BuilderPreferencesV1)
	}
	if err = b.Preferences.UnmarshalSSZ(buf[0:8]); err != nil {
		return err
	}

	// Offset (1) 'Auth'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Auth'
	{
		buf = tail[o1:]
		if b.Auth == nil {
			b.Auth = new(SignedRequestAuthV1)
		}
		if err = b.Auth.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) SizeSSZ() (size int) {
	size = 12

	// Field (1) 'Auth'
	if b.Auth == nil {
		b.Auth = new(SignedRequestAuthV1)
	}
	size += b.Auth.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderPreferencesRequestV1 object with a hasher
func (b *BuilderPreferencesRequestV1) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Preferences'
	if b.Preferences == nil {
		b.Preferences = new(BuilderPreferencesV1)
	}
	if err = b.Preferences.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Auth'
	if err = b.Auth.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
