// Code generated by fastssz. DO NOT EDIT.
// Hash: 09dbd25609c2dc49cd1715fa16f265bed7466672ae2857cecc5e09c902434096
// Version: 0.1.3
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderPreferencesV1 object to a target array
func (b *BuilderPreferencesV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'MaxExecutionPayment'
	dst = ssz.MarshalUint64(dst, uint64(b.MaxExecutionPayment))

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 8 {
		return ssz.ErrSize
	}

	// Field (0) 'MaxExecutionPayment'
	b.MaxExecutionPayment = phase0.Gwei(ssz.UnmarshallUint64(buf[0:8]))

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) SizeSSZ() (size int) {
	size = 8
	return
}

// HashTreeRoot ssz hashes the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderPreferencesV1 object with a hasher
func (b *BuilderPreferencesV1) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'MaxExecutionPayment'
	hh.PutUint64(uint64(b.MaxExecutionPayment))

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
